* Уровень 0 *

In [3]:
import numpy as np

In [8]:
# Диагональная, ортогональная, но не единичная
A = np.array([
    [-1, 0, 0],
    [0, -1, 0],
    [0, 0, -1]
])
B = A.transpose()
A @ B

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [45]:
#Верхнетреугольная и нижнетреугольная ортогональные матрицы
A = np.array([
    [1, 0, 0, 0],
    [0, -1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, -1]
])
B = A.transpose()
print(B)
A @ B


[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0  1  0]
 [ 0  0  0 -1]]


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [63]:
#матрица, у которой det=1, и все элементы !=0
F = np.array([
    [1, 1, 1],
    [2, 1, 2],
    [2, 1, 1]
])
print(np.linalg.det(F))

1.0


In [64]:
m = np.array([
    [2, 2],
    [1, 3]
])

w, v = np.linalg.eig(m)
print(w)
print(v)

[1. 4.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


* Уровень 1 *

** Часть 1 **

In [65]:
M = np.array([
    [1, 2],
    [2, 3]
])

a, U = np.linalg.eig(M)
print(a)
print(U)

[-0.23606798  4.23606798]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [67]:
print(np.array(U.dot(np.diag(a)).dot(U.T), dtype=float))

[[1. 2.]
 [2. 3.]]


** Часть 2 **

In [79]:
from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
from sklearn.metrics import mean_squared_error
import pandas as pd

In [69]:
digits = load_digits()

In [82]:
Numeral = []
PCA_components = []
MSE_value = []

for numeral in range(10):
    X_mnist = digits.images[numeral]
    for i in range(8, 0 , -1):
        pca = PCA(n_components = i)
        X_mnist_reduced = pca.fit_transform(X_mnist)
        X_mnist_recovered = pca.inverse_transform(X_mnist_reduced)
        mse_res = mean_squared_error(X_mnist, X_mnist_recovered)
        Numeral.append(numeral)
        PCA_components.append(i)
        MSE_value.append(mse_res)
        
dict_ = {'Numeral': Numeral, 'Qty PCA components': PCA_components, 'MSE_value': MSE_value}
df = pd.DataFrame(dict_)

In [84]:
df.loc[df['Numeral'] == 7]

Numeral  Qty PCA components     MSE_value
56        7                   8  1.042253e-29
57        7                   7  1.042253e-29
58        7                   6  3.091981e-03
59        7                   5  4.694089e-02
60        7                   4  2.168811e-01
61        7                   3  2.283963e+00
62        7                   2  4.989929e+00
63        7                   1  8.982228e+00